version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: workflows
    groups:
      actions:
        patterns: ["*"]
    labels: ["dependencies"]
    schedule:
      interval: monthly
