version: 2

build:
  os: "ubuntu-22.04"
  apt_packages:
    - libclang
  tools:
    python: "3.11"

python:
  install:
    - requirements: doc/requirements.txt

sphinx:
  configuration: doc/source/conf.py

formats: all
