version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: doc/requirements_docs.txt
    - path: .

sphinx:
  configuration: doc/source/conf.py

formats: all
