name: build and test on macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        cc: [clang]
    steps:
    - uses: actions/checkout@v2
    - name: Install build and test dependencies
      run: |
        brew update
        brew upgrade
        brew autoconf automake libtool

    - name: Build and install library
      run: |
        export CC=${{ matrix.cc }}
        ./autogen.sh
        make
        make install

    - name: Run unit tests
      run: make check
